name: LyaimTech frontend

on: 
    push: 
        branches: [ main ]
        
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code frontend
              uses: actions/checkout@v3

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: | 
                  rohitsamasi555/lyaim-tech-frontend:${{ github.sha }} 
                  rohitsamasi555/lyaim-tech-frontend:latest

            - name: Deploy to VM
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: "3.87.225.63"
                username: "ubuntu" # Your SSH user
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  sudo docker pull rohitsamasi555/lyaim-tech-frontend:latest
                  if 
                    sudo docker ps -a --format '{{.Names}}' | grep -q "^lyaim-frontend$"; 
                  then
                      sudo docker stop lyaim-frontend
                      sudo docker rm lyaim-frontend
                  fi
                  sudo docker run -d --name lyaim-frontend -e BASE_URL="${{ secrets.BASE_URL }}" -p 3000:3000 --restart always rohitsamasi555/lyaim-tech-frontend:latest
                  sudo docker image prune -f
